### PR TITLE
CucumberRunner27

### PR DESCRIPTION
**Pull request by Rusana**
Cont

### CODE REVIEW

**Comment by Berichicko** [comment]
The code is not compiled! Please finish the homework!You got this problem, please correct it.

image

HINT

Please download and check

[Rusana-QA-Automation-Framework-Template.zip](https://github.com/Rusana/Rusana-QA-Automation-Framework-Template/files/14012865/Rusana-QA-Automation-Framework-Template.zip)

**Comment by Berichicko** [comment]
The code is not compiled! Please finish the homework!You got this problem, please correct it.

image

**Step 1**

**class BasePage**

SOLUTION:

image

**Step 2**

**Login.feature**

Add `te$t$tudent`

SOLUTION:

image

RESULT:

image

**Comment by Berichicko** [comment]
The code is not compiled! Please finish the homework!You got this problem, please correct it.

image

**Comment by Berichicko** [comment]
Hello,

I have checked your homework 27, and I wanted to let you know that you're doing great! Keep up the excellent work!
Best wishes from the HW team (Alex, [aliaksandr@testpro.io](mailto:aliaksandr@testpro.io))!

804deb64dc406a20a75da05d91a1a69e

image

**Comment by Rusana** [comment]
Hello, Alexandr! How are you? That is my resume as a common section with
general answers.I have a stupid question )can we Creating and executing for
a  Mobil application testing in Selenium WebDriver using Java (TestNG,
JUnit),
  Cucumber and LambdaTest, Jenkins as a WEb ....?



Rusana Ashurova

Toronto, ON

Cell: (305)742-1989

Email: ***@***.***



                                              QA Automation Engineer.


Summary:

  Quality - focused in QA automation with 5 years of experience
specializing automation and manual testing.

  Creating and executing for a Web and Mobil application testing in
Selenium WebDriver using Java (TestNG, JUnit),

  Cucumber and LambdaTest, Jenkins.


Professional Skills and Tool:

  |  Java

  |  Selenium Grid

  |  Git

  |  Postman

  |  IntelliJ IDEA

  |  Jira, Zephyr

  |  Gradle

  |  Jenkins

  |  Lambda Tests

  |  Selenium Grid


KEY Achievement:

  Overhauled 5 UA automated testing solutions leading to a dramatic 84%
increase in test and over all product quality

  Utilized the Selenium WebDriver Framework with Java to create 1000+
regression test along with functional testing

  uncovering deeply rested BUGs.

  Configured Selenium Grid for parallel testing against multiple
environments and browser.

  Analyzed manual test cases and technical requirements to convert them
into automation test.

  Led a team of 3 members that rewrote regression test cases.


Software Skills:

 Love working with team.


Education:

| Bachelor's Degrees in Psychologist

| Designer

| Business Administrator Transport Company and Dispatch








вт, 6 февр. 2024 г. в 03:52, Aliaksandr (Alex) Zasinets <
***@***.***>:

**Pull request merged**
